# credenciales de postgresql en base64
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # postgres
  POSTGRES_USER: cG9zdGdyZXM=
  # password  
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  # legacy_db
  POSTGRES_DB: bGVnYWN5X2Ri
