name: CI Pipeline
# se ejecuta cuando se hace cada push a develop o feature
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout codigo
      uses: actions/checkout@v3

    # validacion estatica de manifiestos kubernetes
    - name: instalar kubeconform
      run: |
        curl -sSL -o kubeconform.tar.gz \
          https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
        tar -zxvf kubeconform.tar.gz
        sudo mv kubeconform /usr/local/bin/

    - name: validar manifiestos kubernetes
      run: |
        kubeconform -strict -summary kubernetes/*.yaml

    # construccion de imagenes docker
    - name: construir imagen legacy-app
      run: |
        docker build -t legacy-app:latest ./src/legacy-app

    - name: construir imagen new-microservice
      run: |
        docker build -t new-microservice:latest ./src/microservice

    # validar que las imagenes se construyeron
    - name: verificar imagenes
      run: |
        docker images | grep legacy-app
        docker images | grep new-microservice
